/*
 * This is free and unencumbered software released into the public domain.
 * 
 * Anyone is free to copy, modify, publish, use, compile, sell, or
 * distribute this software, either in source code form or as a compiled
 * binary, for any purpose, commercial or non-commercial, and by any
 * means.
 * 
 * In jurisdictions that recognize copyright laws, the author or authors
 * of this software dedicate any and all copyright interest in the
 * software to the public domain. We make this dedication for the benefit
 * of the public at large and to the detriment of our heirs and
 * successors. We intend this dedication to be an overt act of
 * relinquishment in perpetuity of all present and future rights to this
 * software under copyright law.
 * 
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
 * EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
 * MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT.
 * IN NO EVENT SHALL THE AUTHORS BE LIABLE FOR ANY CLAIM, DAMAGES OR
 * OTHER LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE,
 * ARISING FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR
 * OTHER DEALINGS IN THE SOFTWARE.
 * 
 * For more information, please refer to <http://unlicense.org/>
 */

package view;

import controller.Controller;
import java.awt.Component;
import java.awt.GridBagConstraints;
import java.awt.GridBagLayout;
import java.awt.Insets;
import java.awt.event.InputEvent;
import java.awt.event.KeyEvent;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JCheckBox;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JPopupMenu;
import javax.swing.JScrollPane;
import javax.swing.JSpinner;
import javax.swing.JTable;
import javax.swing.JTextField;
import javax.swing.KeyStroke;
import javax.swing.SpinnerNumberModel;
import javax.swing.UIManager;
import javax.swing.WindowConstants;
import javax.swing.border.BevelBorder;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;

/**
 * MainWindow class
 */
public class MainWindow extends JFrame {

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        // Set the native look and feel
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        try {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            Logger.getLogger(MainWindow.class.getName()).log(Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        GridBagConstraints gridBagConstraints;

        queryPanel = new JPanel();
        JLabel codLabel = new JLabel();
        codValue = new JTextField();
        JLabel desLabel = new JLabel();
        desValue = new JTextField();
        consultButton = new JButton();
        updateButton = new JButton();
        batchCheck = new JCheckBox();
        batchValue = new JSpinner();
        scrollPane = new JScrollPane();
        table = new JTable();
        rowCount = new JLabel();
        menuBar = new JMenuBar();
        fileMenu = new JMenu();
        importItem = new JMenuItem();
        JPopupMenu.Separator separator1 = new JPopupMenu.Separator();
        clearFiltersItem = new JMenuItem();
        consultItem = new JMenuItem();
        JPopupMenu.Separator separator2 = new JPopupMenu.Separator();
        exitItem = new JMenuItem();
        connectionMenu = new JMenu();
        connectItem = new JMenuItem();
        disconnectItem = new JMenuItem();
        helpMenu = new JMenu();
        aboutItem = new JMenuItem();

        setDefaultCloseOperation(WindowConstants.EXIT_ON_CLOSE);
        setTitle("Actualizador de Precios");
        setIconImage(new ImageIcon(getClass().getResource("/resources/icon32.png")).getImage());
        setName("mainWindow"); // NOI18N
        getContentPane().setLayout(new GridBagLayout());

        queryPanel.setBorder(BorderFactory.createTitledBorder("Filtros y opciones"));
        queryPanel.setName("queryPanel"); // NOI18N
        queryPanel.setLayout(new GridBagLayout());

        codLabel.setText("Código:");
        codLabel.setName("codLabel"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new Insets(0, 5, 0, 0);
        queryPanel.add(codLabel, gridBagConstraints);

        codValue.setToolTipText("Filtrar por código");
        codValue.setName("codValue"); // NOI18N
        codValue.setActionCommand(codValue.getName());
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 0.1;
        gridBagConstraints.insets = new Insets(0, 5, 0, 5);
        queryPanel.add(codValue, gridBagConstraints);

        desLabel.setText("Descripción:");
        desLabel.setName("desLabel"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new Insets(0, 5, 0, 0);
        queryPanel.add(desLabel, gridBagConstraints);

        desValue.setToolTipText("Filtrar por descripción");
        desValue.setName("desValue"); // NOI18N
        desValue.setActionCommand(desValue.getName());
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(2, 5, 0, 5);
        queryPanel.add(desValue, gridBagConstraints);

        consultButton.setMnemonic('O');
        consultButton.setText("Consultar");
        consultButton.setToolTipText("Consulta con los criterios indicados");
        consultButton.setName("consultButton"); // NOI18N
        consultButton.setActionCommand(consultButton.getName());
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(0, 5, 2, 5);
        queryPanel.add(consultButton, gridBagConstraints);

        updateButton.setMnemonic('P');
        updateButton.setText("Aplicar");
        updateButton.setToolTipText("Aplicar cambios en la base de datos");
        updateButton.setName("updateButton"); // NOI18N
        updateButton.setActionCommand(updateButton.getName());
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new Insets(0, 5, 5, 5);
        queryPanel.add(updateButton, gridBagConstraints);

        batchCheck.setText("Actualizar lote:");
        batchCheck.setName("batchCheck"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new Insets(0, 5, 0, 0);
        queryPanel.add(batchCheck, gridBagConstraints);

        batchValue.setModel(new SpinnerNumberModel(1, 1, 10, 1));
        batchValue.setEnabled(batchCheck.isSelected());
        batchValue.setName("batchValue"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.insets = new Insets(2, 5, 0, 5);
        queryPanel.add(batchValue, gridBagConstraints);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(queryPanel, gridBagConstraints);

        scrollPane.setBorder(null);
        scrollPane.setName("scrollPane"); // NOI18N

        table.setModel(new DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        table.setName("table"); // NOI18N
        scrollPane.setViewportView(table);

        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.fill = GridBagConstraints.BOTH;
        gridBagConstraints.weightx = 1.0;
        gridBagConstraints.weighty = 1.0;
        getContentPane().add(scrollPane, gridBagConstraints);

        rowCount.setBorder(BorderFactory.createBevelBorder(BevelBorder.LOWERED));
        rowCount.setName("rowCount"); // NOI18N
        gridBagConstraints = new GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = GridBagConstraints.HORIZONTAL;
        gridBagConstraints.weightx = 1.0;
        getContentPane().add(rowCount, gridBagConstraints);

        menuBar.setName("menuBar"); // NOI18N

        fileMenu.setMnemonic('A');
        fileMenu.setText("Archivo");
        fileMenu.setToolTipText("");
        fileMenu.setName("fileMenu"); // NOI18N

        importItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_I, InputEvent.CTRL_DOWN_MASK));
        importItem.setText("Importar ...");
        importItem.setName("importItem"); // NOI18N
        importItem.setActionCommand(importItem.getName());
        fileMenu.add(importItem);
        fileMenu.add(separator1);

        clearFiltersItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_ESCAPE, 0));
        clearFiltersItem.setText("Limpiar filtros");
        clearFiltersItem.setName("clearFiltersItem"); // NOI18N
        clearFiltersItem.setActionCommand(clearFiltersItem.getName());
        fileMenu.add(clearFiltersItem);

        consultItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F5, 0));
        consultItem.setText("Consultar");
        consultItem.setName("consultItem"); // NOI18N
        consultItem.setActionCommand(consultItem.getName());
        fileMenu.add(consultItem);

        separator2.setName("separator2"); // NOI18N
        fileMenu.add(separator2);

        exitItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F4, InputEvent.ALT_DOWN_MASK));
        exitItem.setMnemonic('S');
        exitItem.setText("Salir");
        exitItem.setName("exitItem"); // NOI18N
        exitItem.setActionCommand(exitItem.getName());
        fileMenu.add(exitItem);

        menuBar.add(fileMenu);

        connectionMenu.setMnemonic('C');
        connectionMenu.setText("Conexión");
        connectionMenu.setName("connectionMenu"); // NOI18N

        connectItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F11, 0));
        connectItem.setMnemonic('C');
        connectItem.setName("connectItem"); // NOI18N
        connectItem.setActionCommand(connectItem.getName());
        connectionMenu.add(connectItem);

        disconnectItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F12, 0));
        disconnectItem.setMnemonic('D');
        disconnectItem.setText("Desconectar");
        disconnectItem.setName("disconnectItem"); // NOI18N
        disconnectItem.setActionCommand(disconnectItem.getName());
        connectionMenu.add(disconnectItem);

        menuBar.add(connectionMenu);

        helpMenu.setMnemonic('Y');
        helpMenu.setText("Ayuda");
        helpMenu.setName("helpMenu"); // NOI18N

        aboutItem.setAccelerator(KeyStroke.getKeyStroke(KeyEvent.VK_F1, 0));
        aboutItem.setText("Acerca de ...");
        aboutItem.setName("aboutItem"); // NOI18N
        aboutItem.setActionCommand(aboutItem.getName());
        helpMenu.add(aboutItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * Clear filter fields
     */
    public void clearFilters() {
        codValue.setText("");
        desValue.setText("");
        
        codValue.repaint();
        desValue.repaint();
    }
    
    
    /* Getters */
    
    /**
     * Get batch selected status
     * 
     * @return Batch selected status
     */
    public boolean isBatchSelected() {
        return batchCheck.isSelected();
    }
    
    /**
     * Get code filter
     * 
     * @return Code filter
     */
    public String getCod() {
        return codValue.getText();
    }
    
    /**
     * Get description filter
     * 
     * @return Description filter
     */
    public String getDes() {
        return desValue.getText();
    }
    
    /**
     * Get number of batch
     * 
     * @return Number of batch, 0 if is not batch selected
     */
    public int getBatch() {
        int value = (Integer)batchValue.getValue();
        return batchCheck.isSelected() ? value : 0;
    }
    
    /* Setters */
    
    /**
     * Set connected status and enable and disable some components
     * 
     * @param status Connected status
     */
    public void setConnected(boolean status) {
        /* Clear filter fields */
        clearFilters();
        
        /* Query panel */
        for (Component component : queryPanel.getComponents())
            component.setEnabled(component instanceof JSpinner ? batchCheck.isSelected() && status : status);
        
        /* Menus */
        importItem.setEnabled(status);
        clearFiltersItem.setEnabled(status);
        consultItem.setEnabled(status);
        connectItem.setText(status ? "Reconectar ..." : "Conectar ...");
        disconnectItem.setEnabled(status);
        
        /* Clear table if status is not connected */
        if (!status) {
            table.setModel(new DefaultTableModel());
            rowCount.setText(" No conectado ");
        }
    }
    
    /**
     * Enables or disables the menus items
     * 
     * @param status true to enable the items
     */
    public void setMenusEnabled(boolean status) {
        fileMenu.setEnabled(status);
        connectionMenu.setEnabled(status);
        helpMenu.setEnabled(status);
    }
    
    /**
     * Enables or disales the batch value
     */
    public void updateBatchValueStatus() {
        batchValue.setEnabled(batchCheck.isSelected());
    }
    
    /**
     * Set table model with the data
     * 
     * @param tableModel Table model
     */
    public void setTable(TableModel tableModel) {
        table.setModel(tableModel);
        rowCount.setText(" Filas selectionadas: " + tableModel.getRowCount());
        
        table.repaint();
    }
    
    /**
     * Set controller object
     * 
     * @param controller Controller object
     */
    public void setController(Controller controller) {
        /* Menu bar */
        /* File menu */
        fileMenu.addActionListener(controller);
        importItem.addActionListener(controller);
        clearFiltersItem.addActionListener(controller);
        consultItem.addActionListener(controller);
        exitItem.addActionListener(controller);
        
        /* Connection menu */
        connectionMenu.addActionListener(controller);
        connectItem.addActionListener(controller);
        disconnectItem.addActionListener(controller);
        
        /* Help menu  */
        helpMenu.addActionListener(controller);
        aboutItem.addActionListener(controller);
        
        
        /* Query panel */
        /* Text fields */
        codValue.addActionListener(controller);
        desValue.addActionListener(controller);
        batchValue.addChangeListener(controller);
        
        /* Buttons */
        consultButton.addActionListener(controller);
        updateButton.addActionListener(controller);
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private JMenuItem aboutItem;
    private JCheckBox batchCheck;
    private JSpinner batchValue;
    private JMenuItem clearFiltersItem;
    private JTextField codValue;
    private JMenuItem connectItem;
    private JMenu connectionMenu;
    private JButton consultButton;
    private JMenuItem consultItem;
    private JTextField desValue;
    private JMenuItem disconnectItem;
    private JMenuItem exitItem;
    private JMenu fileMenu;
    private JMenu helpMenu;
    private JMenuItem importItem;
    private JMenuBar menuBar;
    private JPanel queryPanel;
    private JLabel rowCount;
    private JScrollPane scrollPane;
    private JTable table;
    private JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
